def get_sim_time(units: str = ...) -> int: ...
def get_time_from_sim_steps(steps: int, units: str) -> int: ...
def get_sim_steps(time: float, units: str = ..., *, round_mode: str = ...) -> int: ...

lazy_property = property
